---
editor_options: 
  markdown: 
    wrap: 72
---

# Current Dissertation

Does Solo Gameplay Replenish Belonging After Social Rejection?

The bi-dimensional rejection taxonomy identifies disengaged-prosocial
responses as an emerging category of behavioral responses to social
rejection [@sunamiBIDimensionalRejectionTaxonomy2020]. Since this category is novel, identifying new
disengaged-prosocial responses benefits the literature. One potential
unexamined disengaged-prosocial response is solo gameplay: gameplays
without any other human players. Solo gameplay is disengaged and
prosocial since players play alone by themselves and satisfy belonging
in an indirect, passive, hands-off manner from the non-human entities in
a game [@sunamiBIDimensionalRejectionTaxonomy2020]. Theoretically, solo gameplay should replenish
belonging via social surrogates [@gabrielSocialSurrogatesRejection2017]. However, no quantitative
studies have tested this possibility. In my dissertation, I examined
whether solo gameplay can replenish belonging after social rejection.

In this chapter, I discuss a theoretical foundation for the hypothesis
that solo gameplay can replenish belonging following social rejection. I
first discuss the social surrogacy hypothesis [@gabrielSocialSurrogatesRejection2017]. This
hypothesis suggests that people can fulfill belonging from *social
surrogates*: targets with only psychological bonds without actual social
interactions. I focus on two types of social surrogates relevant to
single-player games, namely parasocial relationships and social worlds.
For each type of social surrogate, I draw from video game research to
discuss how video games can provide a social surrogate. Finally, I
introduce the research question and the hypotheses of my dissertation.

## The Social Surrogacy Hypothesis: Purely Psychological Bonds that Fulfill Belonging

People can satisfy their fundamental need to belong via
engaged-prosocial behaviors such as affectionate exchanges with one's
romantic partner, family members, and friends [@baumeisterNeedBelongDesire1995].
However, an interaction with a real person is not the only way to
satisfy belonging---people can replenish belonging via
disengaged-prosocial behaviors such as feeling connected with fictional
characters in books [@gabrielSocialSurrogatesRejection2017]. Just as people have used substitutes
to satisfy other fundamental needs (e.g., coca leaves for hunger,
caffeine for sleep), people can use *social surrogates* to substitute
real social connections. Social surrogates are human or non-human
targets to which people form symbolic bonds without actual social
interactions [@derrickSocialSurrogacyHow2009; @gabrielSocialSurrogatesRejection2017]. The social surrogacy
hypothesis suggests three types of social surrogates: parasocial
relationships (e.g., feeling connected to a favorite TV character),
social worlds (e.g., feeling like a member of a collective in a fantasy
novel), and reminders of others (e.g., feeling connected by looking at
photos of loved ones). I focus on parasocial relationships and social
worlds since video games can provide an opportunity for both, as
discussed later. I do not include reminders of others since they are
based on real social relationships by definition, and are thus absent in
solo gameplay.

## Parasocial relationships

### Definition

Parasocial relationships refer to one-way emotional bonds and feelings
of intimacy without an actual social interaction [@gabrielSocialSurrogatesRejection2017;
@knowlesBelongingRegulationUse2013]. People sometimes feel like they are friends with
celebrities (e.g., Cardi B) or fictional characters (e.g., Derrick
Morgan from Criminal Minds); they feel like they "know" the person and
are psychologically connected to them. People even become romantically
attracted to fictional characters [@liebers2017]. Past research showed
that people form parasocial relationships with various targets:
fictional characters in books and TV programs, celebrities, and Formula
1 drivers [@derrick2008; @hartmann2008; @horton1956; @rubin1985;
@rubin1987; @schmid2011].

Parasocial relationships are similar to real social relationships in
some ways. First, people tend to form both real and parasocial
relationships with similar others. In real social relationships, people
form stronger bonds with others who appear similar to themselves than
those who do not [@montoya2008]. Similarly, people form stronger
parasocial relationships with television performers and book characters
when they see similarities in attitudes, beliefs, and values than when
they do not [@liebers2017; @turner1993]. Second, breaking up with or
losing a parasocial relationship partner can be emotionally hurtful as
losing a real relationship [@cohen2003; @eyal2006; @lather2011]. In real
social relationships, people experience distress for breakups and grief
for losing a loved one [@lobb2010; @lundorff2017; @sbarra2006].
Likewise, when the American TV sitcom *Friends* ended, viewers with
stronger parasocial relationships with Friends characters reported
becoming lonelier and missing their favorite character more than those
with weaker parasocial relationships [@eyal2006]. People with stronger
parasocial relationships with the celebrity Robin Williams reported more
grief over Williams' death than those with weaker parasocial
relationships [@cohen2016]. People also experience distress when they
are temporarily separated from a parasocial target, similar to missing a
loved one in real social relationships [@le2008; @le2011]. For instance,
during the writer's strike in 2007--2008 when TV companies stopped
airing new episodes, TV viewers lost opportunities to parasocially
interact with their favorite TV characters. During this time, people
with stronger parasocial relationships with TV characters were more
distressed and lonelier than those with weaker parasocial relationships
[@lather2011].

Despite the similarities, parasocial relationships are different from
real social relationships in at least two ways. First, parasocial
relationships are one-way and nonreciprocal, whereas real social
relationships are two-way and reciprocal. In contrast to a real
relationship where both partners can communicate with each other, in a
parasocial relationship the media consumer is the only one who forms a
psychological bond to the media figure, without an opportunity to
influence the media figure and receive a response [@cohen2014;
@horton1956]. Second, parasocial relationships tend to be weaker in
strength than real social relationships. People reported that they were
less satisfied, less invested, and less committed to parasocial
relationships with their favorite media figure than to an actual
relationship with their close friends and family members [@eyal2012].
Overall, while parasocial relationships can benefit people's belonging,
they may not substitute actual close relationships.

### Parasocial Relationships in Video Games

In the early role-playing and adventure video games of the 1970s, most
non-player characters were enemies (e.g., trolls, dragons, etc.), and
thus players had few opportunities to form emotional bonds with video
game characters. Later in the 1980s, video games began to present
relatable non-player characters. For example, *King's Quest*
[@on-line1984a] included dialogues with the king, the elf, and the
woodcutter, where players could get to know about these non-player
characters. In the 1980-90s, Japanese game developers created the
\_dating games \_genre where players could form strong romantic
relationships with other characters. For example, in *Tokimeki Memorial*
("Heartbeat Memorial"), the player takes the role of a male high school
student who dates female non-player characters to seek *eternal love*
[@corporation1994a; @pollack1996]. A media report even suggested that
some players became so emotionally attached to their favorite characters
that they started to send love letters and birthday cards to the
characters [@pollack1996].

Modern adventure and role-playing games also present relatable
non-player characters with whom players can form parasocial
relationships [@tyack2017]. For example, players of *Mass Effect 2*
[@bioware2010] reported forming intense emotional bonds with characters
(Garrus or Tali) similar to romantic relationships [@burgess2020a].
Among women who played dating games, those with more playtime formed a
stronger parasocial relationship with a virtual romantic partner than
those with less playtime [@song2016]. Thus, people can form parasocial
relationships with non-player characters in video games and possibly
replenish belonging. However, the bulk of research has been anecdotal,
qualitative, and theoretical, and no studies have examined whether
people can rely on parasocial relationships to cope with social
rejection. In the current dissertation, I provide quantitative evidence
on whether parasocial relationships in video games can replenish
belonging after social rejection. Based on the social surrogacy
hypothesis, I hypothesized that rejected people who play a single-player
video game with higher parasocial relationship content would report
higher belonging than those who play a game with lower parasocial
relationship content.

## Social Worlds

### Definition

Social worlds are stories, narratives, and collectives to which people
assimilate [@gabrielSocialSurrogatesRejection2017]. When consuming a narrative (e.g., reading or
watching), people immerse themselves in the story and transport
themselves into the social world described in the narrative
[@gabrielBecomingVampireBeing2011]. As a result, people can assimilate themselves as a
member of the collective in the story---a process called narrative
collective-assimilation [@gabrielSocialSurrogatesRejection2017; @gerrig1993; @green2004;
@mar2008]. For example, participants who read a passage from Harry
Potter reported that they felt like a member of the magical world of
Harry Potter---people felt like being British, able to move an object,
and able to make themselves disappear magically [@gabrielBecomingVampireBeing2011]. On the
other hand, participants who read a passage from Twilight identified
themselves as a vampire---people felt like having sharper teeth and
being able to jump higher and stay awake longer. Thus, people can
immerse and assimilate into a collective in a social world, and
theoretically, can feel belonging. Indeed, people with a higher need to
belong are more likely to immerse themselves in stories than those with
a lower need to belong [@greenwood2009]. Socially rejected people who
recalled their favorite TV program (providing social worlds) reported
higher belonging than those who recalled a non-favorite TV program
[@derrickSocialSurrogacyHow2009].

Researchers have used different terms to describe the process by which
people immerse in a social world, such as *transportation*, *flow*,
*cognitive absorption*, *and* *presence* [@agarwal2000;
@csikszentmihalyi2008; @green2004; @green2000; @patrick2000; @pine1999].
In my dissertation, I use *immersion* as an overarching term to describe
the process whereby players immerse themselves and assimilate to the
collective in a video game.

### Social Worlds in Video Games

Like books, TV shows, and movies, many modern video games provide social
worlds for players to immerse themselves in, assimilate with, and feel
connected to the collectives in the stories
[@bormannImmersedVirtualWorlds2015;
@domschStoryplayingAgencyNarrative2013; @greenTransportationTheory2017].
For example, players can be a soldier of System Alliance in *Mass
Effect*, a citizen of Tamriel in *Elder Scrolls*, a gang in Liberty City
in *Grand Theft Auto*, and a boy from Pallet Town (*Masara* Town) in
*Pokemon*. Video games often provide audio and visual cues that
facilitate the player's immersion into the social world. Players can
hear the noises of busy streets, sounds of trees swinging by wind, or
chatters of other characters. Players see roads, vehicles, houses, and
buildings that represent a collective in the video game. They learn
about the story and feel like being a character in the world as they
experience those visual and audio cues.

Can people replenish belonging by immersing themselves in a social world in a
single-player video game? In one study, half of the participants were
told to ignore the story whereas the other half read a backstory of the
game [@bormannImmersedVirtualWorlds2015]. Then, participants played
*Gone Home*, a single-player adventure game with a rich narrative.
Participants who read the backstory experienced higher immersion and
higher belonging than those who ignored the story
[@bormannImmersedVirtualWorlds2015]. Based on the social surrogacy
hypothesis, I hypothesized that rejected people who play a single-player
video game with higher social worlds content would report higher
belonging than those who play a game with lower social worlds content.

## Focusing on Solo Play

Both single-player and multiplayer games can potentially provide
parasocial relationships and social worlds. For example, players of
massively online multiplayer role-playing games (MMORPG) can experience
social surrogates by feeling a personal connection to Arthas Menethil in
the World of Warcraft or feeling like a member of the race Lalafell in
*Final Fantasy IV*. However, players can also interact with other real
players in multiplayer and thus replenish their belonging via real
social interactions, without social surrogacy [@kowert2015; @vella2015].
Since the goal of my dissertation is to examine playing a video game as
a disengaged-prosocial response without real social interactions, I
exclusively focused on solo gameplay.

## Focusing on Outcome, not Mechanism

In my dissertation, I focused on whether playing a single-player video
game with social surrogates can increase belonging after social
rejection. Since this is the first study to examine this novel
possibility, I did not focus on examining the mechanisms in which
social surrogates can increase belonging, an important area for future
research. Multiple mechanisms are possible for social surrogates to
replenish belonging following social rejection. Social surrogates can
directly replenish belonging as the social surrogacy hypothesis
suggests. Or, social surrogates can replenish belonging via other
intermediary psychological processes. For example, playing a video game
can make the player feel happy, competent, autonomous, self-confident,
or even distracted following social rejection---all of which could
increase belonging [@hales2016; @learySelfesteemInterpersonalMonitor1995; @wesselmann2013;
@williamsOstracismTemporalNeedthreat2009]. While these are all interesting possibilities, the goal
of my dissertation is to test whether social surrogates are effective to
replenish belonging in single-player games. Without knowing whether they
can replenish belonging, any efforts to examine why they do so would be
inefficient. If I find that the social surrogates replenish belonging in
single-player games, then we can start investigating possible
mechanisms. With that being said, I included a few ancillary measures
that assessed some of these possibilities (e.g., enjoyment, valence, and
dominance), but this was not the main goal of this dissertation.

## Do Parasocial Relationships and Social Worlds Influence Each Other?

The social surrogacy hypothesis suggests that parasocial relationships
and social worlds are distinct processes, relatively independent from
each other [@gabrielSocialSurrogatesRejection2017]. Theoretical discussions in the communications
literature support this independence. People can immerse themselves in a
story without forming a parasocial relationship; conversely, people can
form a parasocial relationship without immersing themselves in a story
[@greenTransportationTheory2017]. For example, readers of Harry Potter
can feel like a student at Hogwarts, without feeling close to Harry,
Hermionie, or Ron. Similarly, readers can develop parasocial
relationships with the characters, without feeling like a member of a
collective in the social world.

Although parasocial relationships and social worlds are independent,
they could positively influence each other
[@brownExaminingFourProcesses2015; @vordererEnjoymentHeartMedia2004].
Highly immersed players may form stronger parasocial relationships with
the characters than non-immersed players. Likewise, players with
stronger parasocial relationships with the characters may immerse more
in the story than those with weaker parasocial relationships. Existing
research supports this relationship between parasocial relationships and
social worlds. A theory of media entertainment suggests that people
enjoy media the most when they experience parasocial relationships and
immersion at the same time [@vordererEnjoymentHeartMedia2004]. In a
quantitative study, people who were immersed more in a story reported
stronger parasocial relationships than those who did not
[@slaterExtendingConceptualizationMeasurement2018]. After watching a
novel TV episode, people who formed stronger parasocial relationships
with the characters reported feeling more immersed in the story than
those who formed weaker parasocial relationships
[@ericksonExperimentalExaminationBinge2019]. Taken together, I
hypothesize that the effects of parasocial relationships and social
worlds can add up to benefit belonging (Hypothesis 4). However, the
social surrogacy hypothesis makes no clear prediction about whether the
relationship between parasocial relationships and social worlds would be
additive or synergistic. Thus, I treated this hypothesis as ancillary.

## Current Dissertation

In this dissertation, I asked whether solo gameplay can replenish
belonging after social rejection---whether socially rejected people
could restore their sense of belonging by playing a video game in
single-player mode. I start my dissertation by validating a new measure
of state belonging, the Heart Manikin (Study 1), because a flexible
state measure of belonging does not currently exist. I used this measure
as a primary outcome throughout my dissertation.

In Study 2, I asked rejected participants to write about a time they
played a video game with social surrogates vs. a video game without
social surrogates. I hypothesized that rejected people who write about
their regularly played video game with social surrogates would report
higher belonging than those who write about a regularly played game
without social surrogates (Hypothesis 1).

Contrasting social surrogate video games and non-social surrogate video
games in Study 2 provides preliminary evidence of whether rejected
people can replenish their belonging by social surrogates in
single-player games. However, whether parasocial relationships, social
worlds, or a combination of the two influenced belonging remains
unknown. To resolve these issues, I asked participants to play a novel,
custom single-player game with higher vs. lower parasocial relationships
and social world contents in Study 3. I hypothesized that rejected
people who play a video game with higher parasocial relationship content
would report higher belonging than those who play a video game with
lower parasocial relationship content (Hypothesis 2). Similarly,
rejected people who play a video game with higher social world content
would report higher belonging than those who play a video game with
lower social world content (Hypothesis 3). As an ancillary hypothesis, I
expected an additive effect of parasocial relationships and social
worlds: rejected people who play a video game with higher parasocial
content and higher social world contents would report the highest
belonging among all groups (Hypothesis 4).

## Open Science Statement

To reduce biases from post-hoc, data-dependent inferences, and
researchers' degrees of freedom, I pre-registered my hypotheses and
research plans on the Open Science Framework. To maximize the
transparency and reproducibility of the results, I uploaded materials,
analysis scripts, and de-identified data to the Open Science Framework
(<https://osf.io/hydxk/>) and GitHub
(<https://github.com/nsunami/dissertation>) so that other researchers
can reproduce and verify the results.
