project:
  type: book
  output-dir: docs

book:
  title: "Playing Alone, Feeling Connected: Do Single-Player Video Games with Social Surrogates Replenish Belonging After Social Rejection?"
  author: "Naoyuki Sunami"
  date: "1/10/2025"
  chapters:
    - index.qmd
    - 01-Bi-DR.qmd
    - 02-Current-Dissertation.qmd
    - 03-Study-1.qmd
    - 04-Study-2.qmd
    - 05-Study-3.qmd
    - 06-General-Discussion.qmd
    - 07-References.qmd

bibliography:
  - references.bib
  - packages.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: source
