services:
  rstudio:
    image: "ghcr.io/nsunami/dissertation:main"
    ports:
      - 8787:8787
    volumes:
      - ./:/home/rstudio/dissertation/
    environment:
      - PASSWORD=changeme # default username is rstudio

