---
title           : "Playing Alone, Feeling Connected: Do Single-Player Video Games with Social Surrogates Replenish Belonging After Social Rejection?"
shorttitle      : "Playing Alone, Feeling Connected"
date            : "`r Sys.setlocale('LC_TIME', 'C'); format(Sys.time(), '%d\\\\. %B %Y')`"

author: 
  - name        : Naoyuki Sunami
    affiliation : 1

affiliation:
  - id          : 1
    institution : University of Delaware

output: prereg::cos_prereg
bibliography      : "preregistration.bib"
---
<!-- Workaround for CSLReferences Error -->
<!-- \newlength{\cslhangindent} -->
<!-- \setlength{\cslhangindent}{1.5em} -->
<!-- \newenvironment{CSLReferences}% -->
<!-- {\setlength{\parindent}{0pt}% -->
<!-- \everypar{\setlength{\hangindent}{\cslhangindent}}\ignorespaces}% -->
<!-- {\par} -->



# Study Information

## Title
<!-- Provide the working title of your study. It may be the same title that you submit for publication of your final manuscript, but it is not a requirement. The title should be a specific and informative description of a project. Vague titles such as 'Fruit fly preregistration plan' are not appropriate.

Example: Effect of sugar on brownie tastiness. -->

`r rmarkdown::metadata$title`


## Description
<!-- Please give a brief description of your study, including some background, the purpose of the of the study, or broad research questions. The description should be no longer than the length of an abstract. It can give some context for the proposed study, but great detail is not needed here for your preregistration.

Example: Though there is strong evidence to suggest that sugar affects taste preferences, the effect has never been demonstrated in brownies. Therefore, we will measure taste preference for four different levels of sugar concentration in a standard brownie recipe to determine if the effect exists in this pastry. -->


*Note: This document is a reformatted version of the dissertation proposal available at https://osf.io/jenqd/. Please see the proposal document for more detailed descriptions.*

People have a fundamental need to belong—to be accepted, loved, and cared for. The COVID-19 pandemic has threatened people’s sense of belonging since people had to isolate themselves from others due to the stay-at-home orders. At the same time in early 2020, people started to spend more time playing video games; sales and consumption of video games skyrocketed, breaking previous records worldwide. Existing theoretical perspectives suggest one possible reason for this popularity: video games, including single-player video games, may help people feel socially connected. For example, according to the bi-dimensional rejection taxonomy, solo gameplay is a disengaged prosocial response, an attempt to replenish belonging in a hands-off, indirect manner. In addition, according to the social surrogacy hypothesis, solo gameplay can provide social surrogates, symbolic bonds that can replenish belonging. Players can form parasocial relationships (one-way psychological bonds) with a non-player character in the game; players can also immerse themselves in the social worlds and feel like a member of a collective presented in the video game. Although existing theories and qualitative evidence suggest that solo gameplay can benefit belonging, quantitative evidence is lacking to support this prediction. In this dissertation, I will examine whether solo gameplay can replenish belonging after social rejection. In Study 1, I will validate the Heart Manikin—a single-item measure of state belonging, which I will use in the subsequent studies. In Study 2, rejected participants will recall their time playing a video game with vs. without social surrogates. In Study 3, rejected participants will play a custom video game that manipulates parasocial relationships and social worlds. Across studies, I expect that rejected participants who experience parasocial relationships and social worlds will report higher belonging than those who do not. The results will contribute to the bi-dimensional rejection taxonomy, the social surrogacy hypothesis, and the video games literature.


## Hypotheses
<!-- List specific, concise, and testable hypotheses. Please state if the hypotheses are directional or non-directional. If directional, state the direction. A predicted effect is also appropriate here. If a specific interaction or moderation is important to your research, you can list that as a separate hypothesis.

Example: If taste affects preference, then mean preference indices will be higher with higher concentrations of sugar. -->

### Study 2
1. Rejected people who write about their favorite video games with social surrogates will report higher belonging than those who write about a non-favorite game. This hypothesis is directional. 

### Study 3
2. I hypothesize that rejected people who play a video game with higher parasocial relationship content will report higher belonging than those who play a video game with lower parasocial relationship content. This hypothesis is directional.

3. Rejected people who play a video game with higher social world content will report higher belonging than those who play a video game with lower social world content. This hypothesis is directional.

4. As an ancillary hypothesis, I expect an additive effect of parasocial relationships and social worlds: rejected people who play a video game with higher parasocial content and higher social worlds contents will report the highest belonging among all groups. This hypothesis is directional.


# Design Plan
<!-- In this section, you will be asked to describe the overall design of your study. Remember that this research plan is designed to register a single study, so if you have multiple experimental designs, please complete a separate preregistration. -->


## Study type


- Study 1 - **Observational Study**
- Study 2 - **Experiment**
- Study 3 - **Experiment**

**Experiment**. A researcher randomly assigns treatments to study subjects, this includes field or lab experiments. This is also known as an intervention experiment and includes randomized controlled trials.

**Observational Study**. Data is collected from study subjects that are not randomly assigned to a treatment. This includes surveys, natural experiments, and regression discontinuity designs.

**Meta-Analysis**. A systematic review of published studies.

**Other**. Please explain.


## Blinding
<!-- Blinding describes who is aware of the experimental manipulations within a study. Select all that apply. Is there any additional blinding in this study? -->

### Study 1
N/A - No experimental manipulation.

### Studies 2 & 3
- For studies that involve human subjects, they will not know the treatment group to which they have been assigned.

- Personnel who interact directly with the study subjects (either human or non-human subjects) will not be aware of the assigned treatments.


## Study design
<!-- Describe your study design. Examples include two-group, factorial, randomized block, and repeated measures. Is it a between (unpaired), within-subject (paired), or mixed design? Describe any counterbalancing required. Typical study designs for observation studies include cohort, cross sectional, and case-control studies.

This question has a variety of possible answers. The key is for a researcher to be as detailed as is necessary given the specifics of their design. Be careful to determine if every parameter has been specified in the description of the study design. There may be some overlap between this question and the following questions. That is OK, as long as sufficient detail is given in one of the areas to provide all of the requested information. For example, if the study design describes a complete factorial, 2 X 3 design and the treatments and levels are specified previously, you do not have to repeat that information.

Example: We have a between subjects design with 1 factor (sugar by mass) with 4 levels. -->

### Study 1
The study is a cross-sectional design.

### Study 2
The study is a two-group between-subjects design (Video Game Type: Social Surrogate vs. Non-Social Surrogate). 

### Study 3
The study is a 2 (Parasocial Relationships: High vs. Low) x 2 (Social Worlds: High vs. Low) between-subjects design. 

## Randomization
<!-- If you are doing a randomized study, how will you randomize, and at what level? Typical randomization techniques include: simple, block, stratified, and adaptive covariate randomization. If randomization is required for the study, the method should be specified here, not simply the source of random numbers.

Example: We will use block randomization, where each participant will be randomly assigned to one of the four equally sized, predetermined blocks. The random number list used to create these four blocks will be created using the web applications available at http://random.org. -->

### Study 1
No randomization (cross-sectional design).

### Studies 2 & 3
I will use the randomization feature of Qualtrics with an option to evenly distribute participants across conditions. 




# Sampling Plan
<!-- In this section we’ll ask you to describe how you plan to collect samples, as well as the number of samples you plan to collect and your rationale for this decision. Please keep in mind that the data described in this section should be the actual data used for analysis, so if you are using a subset of a larger dataset, please describe the subset that will actually be used in your study. -->



## Existing data
<!-- Preregistration is designed to make clear the distinction between confirmatory tests, specified prior to seeing the data, and exploratory analyses conducted after observing the data. Therefore, creating a research plan in which existing data will be used presents unique challenges. Please select the description that best describes your situation. Please do not hesitate to contact us if you have questions about how to answer this question (prereg@cos.io). -->

### Study 1 
**Registration following analysis of the data**. As of the date of submission, you have accessed and analyzed some of the data relevant to the research plan. This includes preliminary analysis of variables, calculation of descriptive statistics, and observation of data distributions. Please see cos.io/prereg for more information.

### Studies 2 & 3
**Registration prior to creation of data**. As of the date of submission of this research plan for preregistration, the data have not yet been collected, created, or realized. 


## Explanation of existing data
<!-- If you indicate that you will be using some data that already exist in this study, please describe the steps you have taken to assure that you are unaware of any patterns or summary statistics in the data. This may include an explanation of how access to the data has been limited, who has observed the data, or how you have avoided observing any analysis of the specific data you will use in your study.

An appropriate instance of using existing data would be collecting a sample size much larger than is required for the study, using a small portion of it to conduct exploratory analysis, and then registering one particular analysis that showed promising results. After registration, conduct the specified analysis on that part of the dataset that had not been investigated by the researcher up to that point.

Example: An appropriate instance of using existing data would be collecting a sample size much larger than is required for the study, using a small portion of it to conduct exploratory analysis, and then registering one particular analysis that showed promising results. After registration, conduct the specified analysis on that part of the dataset that had not been investigated by the researcher up to that point. -->

### Study 1
I will use five existing datasets to validate the Heart Manikin. I have not analyzed data from three of the studies (RPR, RAIv1, and ARv1). I was not the study lead of these studies. 

I led the NPSv2 and EVv1 studies. However, I have not taken a look at the relationship between the Heart Manikin scores and other variables in the study.


## Data collection procedures
<!-- Please describe the process by which you will collect your data. If you are using human subjects, this should include the population from which you obtain subjects, recruitment efforts, payment for participation, how subjects will be selected for eligibility from the initial pool (e.g. inclusion and exclusion rules), and your study timeline. For studies that donÍt include human subjects, include information about how you will collect samples, duration of data gathering efforts, source or location of samples, or batch numbers you will use.

The answer to this question requires a specific set of instructions so that another person could repeat the data collection procedures and recreate the study population. Alternatively, if the study population would be unable to be reproduced because it relies on a specific set of circumstances unlikely to be recreated (e.g., a community of people from a specific time and location), the criteria and methods for creating the group and the rationale for this unique set of subjects should be clear.

Example: Participants will be recruited through advertisements at local pastry shops. Participants will be paid $10 for agreeing to participate (raised to $30 if our sample size is not reached within 15 days of beginning recruitment). Participants must be at least 18 years old and be able to eat the ingredients of the pastries. -->

### Study 1
N/A - The data have already been collected

### Study 2
I will recruit 344 participants from Prolific. Participants will receive \$2.40 ($9.60 per hour rate x 15 minutes) for compensation. Only participants who have regularly played both video games with social surrogates and video games without social surrogates will be eligible to participate. In a screening survey, participants will first see the description about single-player video games, and indicate whether they regularly played any video games with social surrogates and without social surrogates:

>Video games can be played by yourself, where you are not interacting or playing with any other real people (single player modes). Others have the option to play or interact with other real people (multiplayer). We want you to exclusively focus on games that have a single player mode. There are lots of different genres of single player games. 

>[Social Surrogate Games]
One genre is single player role playing games (RPGs). These games always have stories and characters (NPCs), and a storyline about the characters that progresses throughout the game.  Classic examples of this type of game are Mass Effect, Zelda, Final Fantasy (single-player version), and Witcher.  Question: Have you ever regularly played a video game from this genre? (Yes/No)

>[Non-Social Surrogate Games]
Other genres do not have these features, meaning they lack a storyline or NPCs and are largely games that focus on the mechanics of completing a specific task like a puzzle, beating the clock while completing a task, or earning points by doing a task. Classic examples are Poker, Solitaire, Tetris, or sports games that do not have teams like Pro Skater (skateboarding), Lonely Mountains Downhill (off-road biking). Question: Have you ever regularly played a video game from these genres? (Yes/No)

Only participants who indicate yes to both questions will be invited to participate in the study. For social surrogate games, I focused on RPGs because people form strong parasocial relationships with other non-player characters, and people become immersed in the social worlds and stories presented in RPGs. 



### Study 3 

## Sample size
<!-- Describe the sample size of your study. How many units will be analyzed in the study? This could be the number of people, birds, classrooms, plots, interactions, or countries included. If the units are not individuals, then describe the size requirements for each unit. If you are using a clustered or multilevel design, how many units are you collecting at each level of the analysis? For some studies, this will simply be the number of samples or the number of clusters. For others, this could be an expected range, minimum, or maximum number.

Example: Our target sample size is 280 participants. We will attempt to recruit up to 320, assuming that not all will complete the total task. -->

- Study 1: N/A - I'm using existing datasets.
- Study 2: The target sample size is 344 participants. 
- Study 3: The target sample size is 344 participants.


## Sample size rationale
<!-- This could include a power analysis or an arbitrary constraint such as time, money, or personnel. This gives you an opportunity to specifically state how the sample size will be determined. A wide range of possible answers is acceptable; remember that transparency is more important than principled justifications. If you state any reason for a sample size upfront, it is better than stating no reason and leaving the reader to "fill in the blanks." Acceptable rationales include: a power analysis, an arbitrary number of subjects, or a number based on time or monetary constraints.

Example: We used the software program G*Power to conduct a power analysis. Our goal was to obtain .95 power to detect a medium effect size of .25 at the standard .05 alpha error probability. -->

### Study 1
N/A - I'm using existing datasets for this study.

### Study 2
To my knowledge, only one study tested whether recalling a media with or without social surrogates replenished belonging following social rejection @derrickSocialSurrogacyHow2009 (Derrick et al., 2009, Study 2). I will not use the effect size reported in this study for the following reasons. First, an effect size observed in a single study can be upwardly biased and unreliable (Lakens, 2017; Lane & Dunlap, 1978). Second, the media used in the original study was a TV program, not a video game, and thus the effect size may not be compatible. 

Instead, I again use an average effect size estimate (r = .21) across 474 meta-analyses as a starting point (Richard et al., 2003) consistent with the procedure in Study 1. As mentioned, the safeguarded target effect size was Cohen’s d = 0.35. With 90% power to reduce Type II error and 5% alpha by convention, I plan to recruit 344 (172 per group) participants to detect the effect size of d = 0.35 in a two-group design. I will also consider this effect size as the smallest effect size of interest for the equivalence test. Any effect sizes smaller than d = 0.35 will be considered theoretically equivalent to zero in the context of the current study. 

### Study 3
No estimate for the effect size for this study is available, and thus I use the safeguarded effect size in Study 2 as the target effect size (d = 0.35). The current study is a 2 (Parasocial Relationships: High vs. Low) x 2 (Social Worlds: High vs. Low) between-subjects design. I follow a recommendation to base the patterns of group mean differences to estimate an effect size (Lakens & Caldwell, 2019). For the purpose of the current power analysis, I treat Cohen’s d as the differences in the group means by assuming the pooled standard deviation of 1. I used the Superpower R package to perform power analysis (Lakens & Caldwell, 2019).

Since the main goal of the study is to test the effects of parasocial relationships and social worlds on belonging, I calculated the required sample size based on the main effect of each. I assumed that the main effects of the parasocial relationship manipulation and the social world manipulation will each have an effect size of d = 0.35 (Hypotheses 2 and 3). The resulting target sample size to achieve .90 power and .05 alpha is 344 participants in total (86 per condition x 4 conditions). This sample size is enough to detect d = 0.50 with .90 power and .05 alpha for the ancillary Hypothesis 4 (86 per group). See Figure 7 for the expected pattern of the means used for the power analysis.

## Stopping rule
<!-- If your data collection procedures do not give you full control over your exact sample size, specify how you will decide when to terminate your data collection. 

You may specify a stopping rule based on p-values only in the specific case of sequential analyses with pre-specified checkpoints, alphas levels, and stopping rules. Unacceptable rationales include stopping based on p-values if checkpoints and stopping rules are not specified. If you have control over your sample size, then including a stopping rule is not necessary, though it must be clear in this question or a previous question how an exact sample size is attained.

Example: We will post participant sign-up slots by week on the preceding Friday night, with 20 spots posted per week. We will post 20 new slots each week if, on that Friday night, we are below 320 participants. -->


For Studies 2 and 3, I plan to stop recruitment when the sample size reaches the target sample size after exclusions. 


# Variables
<!-- In this section you can describe all variables (both manipulated and measured variables) that will later be used in your confirmatory analysis plan. In your analysis plan, you will have the opportunity to describe how each variable will be used. If you have variables which you are measuring for exploratory analyses, you are not required to list them, though you are permitted to do so. -->


## Manipulated variables
<!-- Describe all variables you plan to manipulate and the levels or treatment arms of each variable. This is not applicable to any observational study. For any experimental manipulation, you should give a precise definition of each manipulated variable. This must include a precise description of the levels at which each variable will be set, or a specific definition for each categorical treatment. For example, “loud or quiet,” should instead give either a precise decibel level or a means of recreating each level. 'Presence/absence' or 'positive/negative' is an acceptable description if the variable is precisely described.

Example: We manipulated the percentage of sugar by mass added to brownies. The four levels of this categorical variable are: 15%, 20%, 25%, or 40% cane sugar by mass. -->


#### Social Rejection Induction (not a manipulation)
I will induce the feelings of social rejection the social rejection essay used in a preivous study (Sunami et al., 2019). All participants will write about a time when they felt rejected by a person or a group of their own age (excluding romantic rejection) for 5 minutes:

>We'd like you to write about a time when you felt rejected or excluded by a person or a group about your own age. By "felt rejected" we mean that you felt like a person or persons did not value you or your relationship. That is, describe an episode in which you wanted to spend time with or do something with someone, and that person or persons did not let you do so. Make sure to be as detailed as possible and describe not only what happened, but also how you felt. If the rejection is by an organized group of people, make sure it is of people about your same age. For example, being rejected from a college or job is NOT what we are asking about. Please do NOT describe a romantic rejection, if possible.


### Study 2 Manipulation - Social Surrogacy Essay
After completing the social rejection essay, participants will be randomly assigned to either the social surrogacy condition or the non-social surrogacy condition in the video game essay task, adapted from the previous study (Derrick et al., 2009). Participants will spend 5 minutes writing the essay. In the social surrogacy condition, participants will be asked to write about a time they played the video game with social surrogates nominated earlier:

> Please think of a time when you played X [the social surrogacy video game]. Who is (are) your favorite character(s)? What was the storyline of the game you are thinking of? What happened to your favorite character(s)? How did the gameplay make you feel? Write about everything you can remember about this particular game. Be as detailed as possible and try to relive playing the game in your mind as you write this description. You will spend 5 minutes writing about this.

In the non-social surrogate video game condition, participants will be asked to write about a time they played the non-social surrogate game: 

>Please think of a time when you played X [the non-social surrogate game]. What was (were) the goal(s)? What tasks were you supposed to complete? What was involved in completing the tasks?  How did the gameplay make you feel? Write about everything you can remember about this particular gameplay. Be as detailed as possible and try to relive playing the game in your mind as you write this description. You will spend 5 minutes writing about this.

### Study 3 Manipulation - Social Surrogacy Video Games
After completing the social rejection essay, participants will play a custom single-player video game, called Shadows of Gaki, developed for this study on RPG Maker (KADOKAWA Corporation, 2015). I will program the video game to independently manipulate parasocial relationships and social worlds. In this game, the player takes the role of Higra, the main character who will solve the mystery of a plaque affecting the village of Azmar. I will set the gender of the main player character as female for two reasons. First, past research showed that players adopt the characteristics of the player character and change how they play the game accordingly (called the Proteus effect)—such as killing more when playing a male character, and healing more when playing a female character (Yee et al., 2011). I will hold the gender of the player character constant in my game to avoid any influence from the Proteus effect. Second, women tend to prefer a female character over a male character whereas men do not have preferences (Paik & Shi, 2013; Ratan et al., 2019). Thus, both female and male participants may like playing a female player character. For these reasons, I will hold the gender of the player character female for all participants. 

The contents presented in this single-player game will vary depending on the experimental conditions. I will manipulate the parasocial relationships via the presence of the companion non-player character Sashu. In the high parasocial relationship condition, the player will have an opportunity to form a parasocial relationship with Sashu. Sashu will guide the player throughout the gameplay and present instructions. In the low parasocial relationship condition, Sashu will not be present in the gameplay, and instructions will be delivered on-screen directly to the player. 

I will manipulate the social worlds via the opportunities for immersing into the story of the video game, and thus facilitating the collective assimilation (Gabriel & Valenti, 2017; Gabriel & Young, 2011). In the high social world condition, the player will be presented with story components—they will learn how the player character decides to help the village of Azmar and the story about the calamity Gaki, etc. In the low social world condition, the player will not be presented with these storytelling components. 



## Measured variables
<!-- Describe each variable that you will measure. This will include outcome measures, as well as any predictors or covariates that you will measure. You do not need to include any variables that you plan on collecting if they are not going to be included in the confirmatory analyses of this study.

Observational studies and meta-analyses will include only measured variables. As with the previous questions, the answers here must be precise. For example, 'intelligence,' 'accuracy,' 'aggression,' and 'color' are too vague. Acceptable alternatives could be 'IQ as measured by Wechsler Adult Intelligence Scale' 'percent correct,' 'number of threat displays,' and 'percent reflectance at 400 nm.'

Example: The single outcome variable will be the perceived tastiness of the single brownie each participant will eat. We will measure this by asking participants ‘How much did you enjoy eating the brownie’ (on a scale of 1-7, 1 being 'not at all', 7 being 'a great deal') and 'How good did the brownie taste' (on a scale of 1-7, 1 being 'very bad', 7 being 'very good'). -->

### Study 1
Below are the tables of the measures included in each sub-studies.

#### Study 1a

**Table 1** _Study 1a: Summary of Measures_

| Measure | Construct | Validity | Citation |
| --- | --- | --- | --- |
| Self-Assessment Manikin |
| Valence | State valence | Con. | Bradley &amp; Lang, 1994 |
| Arousal | State arousal | Dis. | Bradley &amp; Lang, 1994 |
| Dominance | State dominance | Dis. | Bradley &amp; Lang, 1994 |
| Center for Epidemiologic Studies Depression Scale (CES-D) | Depressive symptoms | Con. (R) | Radloff, 1977 |
| Beliefs about Biological Differences between Blacks and Whites Scale | False beliefs about biological differences between Black and White people | Dis | Hoffman et al., 2016 |
| Interpersonal Reactivity Scale | Tendency to react to another person&#39;s experience | Dis. | Davis, 1980 |
| Self-Monitoring Scale | Tendency to self-observe and control one&#39;s behavior according to social appropriateness | Dis. | Snyder, 1974 |
| Paradox Mindset Scale | Tendency to accept and get excited by tensions | Dis. | Miron-Spektor et al., 2018 |
| Integrative Complexity Scale | Capacity to acknowledge the competing opinions | Dis. | Zhang et al., 2015 |
| Multiple Identity Scale | Membership to different social groups | Dis. | Haslam et al., 2008 |

 _Note._ Con. = Convergent Validity. Dis. = Discriminant Validity. (R) = Reverse association.

#### Study 1b

**Table 2** _Study 1b: Summary of Measures_ 

| Measure | Construct | Validity | Citation |
| --- | --- | --- | --- |
| Self-Assessment Manikin: Valence | State valence | Con. | Bradley &amp; Lang, 1994 |
| --- | --- | --- | --- |
| MacArthur Scale of Subjective Social Status | Subjective social status | Dis. | Adler et al., 2000 |
| PROMIS—Short Form 8a |
| Social Isolation | Social isolation | Con. (R) | Cella et al., 2019; Hahn et al., 2014 |
| Emotional Support | Emotional support | Con. | Cella et al., 2019; Hahn et al., 2014 |
| Informational Support | Informational support | Con. | Cella et al., 2019; Hahn et al., 2014 |
| Couples Satisfaction Index | Romantic relationship quality | Con. | Funk &amp; Rogge, 2007 |
| Inclusion of Other in Self Scale | Closeness between the self and the other person | Con. | Aron et al., 1992 |
| Partner Responsiveness Scale | Romantic partner responsiveness | Con. | Gable et al., 2012 |
| Relationship Conflict Scale | Conflicts in a romantic relationship | Con. (R) | Ad-hoc |
| Ostracism from Romantic Partner Scale | Ostracism from a romantic partner | Con. (R) | Ad-hoc |
| Abusive Behavior Inventory—Revised |
| Psychological Abuse | Perpetration of psychological abuse against a romantic partner | Dis. | Postmus et al., 2015 |
| Physical Abuse | Physical abuse perpetration against a romantic partner | Dis. | Postmus et al., 2015 |
| Controlling Behavior Scale—Modified |
| Economic Control | Perpetration of economic control | Dis. | Graham-Kevan &amp; Archer, 2003 |
| Threats | Perpetration of threats | Dis. | Graham-Kevan &amp; Archer, 2003 |
| Intimidation | Perpetration of intimidation | Dis. | Graham-Kevan &amp; Archer, 2003 |
| Emotional Control | Perpetration of emotional control | Dis. | Graham-Kevan &amp; Archer, 2003 |
| Isolation | Perpetration of isolation | Dis. | Graham-Kevan &amp; Archer, 2003 |
| Modified Food Craving Questionnaire—Trait Version | Food craving | Dis. | Cepeda-Benito et al., 2000 |
| Dietary Social Support Scale | Support from one&#39;s romantic partner about eating | Dis. | Ad-hoc |
| Body Image Questionnaire | Body image | Dis. | Ad-hoc |
| Godin Leisure-Time Exercise Questionnaire | Physical activity | Dis. | Godin, 2011; Godin &amp; Shephard, 1985 |
| PROMIS Sleep Disturbance—Short Form 4a | Sleep disturbance | Dis. | Cella et al., 2019 |
| Single-Item Narcissism Scale | Narcissism | Dis. | Konrath et al., 2014 |
| Perceived Stress Scale | Perceived stress | Dis. | S. Cohen et al., 1983 |

_Note._ Con. = Convergent Validity. Dis. = Discriminant Validity. (R) = Reverse association.

#### Study 1c

**Table 3** _Study 1c: Summary of Measures_

| Measure | Construct | Validity | Citation |
| --- | --- | --- | --- |
| Self-Assessment Manikin |
| --- |
| Valence (Times 1, 2, &amp; 3) | State valence | Con. | Bradley &amp; Lang, 1994 |
| Arousal (Time 2) | State arousal | Dis. | Bradley &amp; Lang, 1994 |
| Dominance (Time 2) | State dominance | Dis. | Bradley &amp; Lang, 1994 |
| Modified Need-Threat Scale—Essay Version (Time 2) |
| Belonging | Belonging | Con. | Williams, 2009 |
| Self-Esteem | Self-esteem | Con. | Williams, 2009 |
| Control | Control | Dis. | Williams, 2009 |
| Meaningful Existence | Meaning existence | Dis. | Williams, 2009 |
| MacArthur Scale of Subjective Social Status (Time 3) | Subjective social status | Dis. | Adler et al., 2000 |

_Note._ Con. = Convergent Validity. Dis. = Discriminant Validity. (R) = Reverse association.


#### Study 1d

**Table 4** _Summary of Measures for Study 1d_

| Measure | Construct | Validity | Citation |
| --- | --- | --- | --- |
| Self-Assessment Manikin (Times 1, 2, 3, &amp; 4) |
| --- |
| Valence | State valence | Con. | Bradley &amp; Lang, 1994 |
| Arousal | State arousal | Dis. | Bradley &amp; Lang, 1994 |
| Dominance | State dominance | Dis. | Bradley &amp; Lang, 1994 |
| Rosenberg Self-Esteem Scale (Time 1) | Self-esteem | Con. | Rosenberg, 1965a |
| Need for Closure Scale (Time 1) | Desire for an answer on any topic | Dis. | Roets &amp; Van Hiel, 2011 |
| Modified Need-Threat Scale (Times 3 &amp; 4) |
| Belonging | Belonging | Con. | Williams, 2009 |
| Self-Esteem | Self-esteem | Con. | Williams, 2009 |
| Control | Control | Dis. | Williams, 2009 |
| Meaningful Existence | Meaning existence | Dis. | Williams, 2009 |
| Social Judgment Survey (Time 4) | Adherence to the traditional cultural values | Dis. | Proulx &amp; Heine, 2008; Rosenblatt et al., 1989 |

_Note._ Con. = Convergent Validity. Dis. = Discriminant Validity. (R) = Reverse association.




#### Study 1e 

**Table 5** _Study 1c: Summary of Measures_ 

| Measure | Construct | Validity | Citation |
| --- | --- | --- | --- |
| Self-Assessment Manikin (Times 1, 2, 3, 4, 5, &amp; 6) |
| --- |
| Valence | State valence | Con. | Bradley &amp; Lang, 1994 |
| Arousal | State arousal | Dis. | Bradley &amp; Lang, 1994 |
| Dominance | State dominance | Dis. | Bradley &amp; Lang, 1994 |
| Experiences in Close Relationships Scale—Short Form (Time 1) |
| Avoidance | Attachment avoidance | Con. (R) | Wei et al., 2007 |
| Anxiety | Attachment anxiety | Con. (R) | Wei et al., 2007 |
| Fear of Negative Evaluation Scale—Brief Version (Time 1) | Apprehension in expecting negative judgment from others | Con. (R) | Leary, 1983 |
| Rosenberg Self-Esteem Scale (Time 1) | Self-esteem | Con. | Rosenberg, 1965a |
| MacArthur Scale of Subjective Social Status (Time 1) | Subjective social status | Dis. | Adler et al., 2000 |
| Rejection Sensitivity Questionnaire—Short Version (Time 1) | Rejection sensitivity | Con. (R) | Downey &amp; Feldman, 1996; Romero-Canyas et al., 2010 |
| Modified Need-Threat Scale (Times 3 &amp; 5) |
| Belonging | Belonging | Con. | Williams, 2009 |
| Self-Esteem | Self-esteem | Con. | Williams, 2009 |
| Control | Control | Dis. | Williams, 2009 |
| Meaningful Existence | Meaning existence | Dis. | Williams, 2009 |

_Note._ Con. = Convergent Validity. Dis. = Discriminant Validity. (R) = Reverse association.


### Study 2
After completing the video game essay, participants will complete the Heart Manikin (Time 2), the modified Inclusion of Self in Other Scale (Aron et al., 1992), the modified Parasocial Interaction—Process Scale (Schramm & Hartmann, 2008), the modified Single-Item Immersion Scale (Reysen et al., 2019), the modified Narrative Engagement Scale (Busselle & Bilandzic, 2009), and the Enjoyment Subscale of the Game User Experience Satisfaction Scale (GUESS; Phan et al., 2016). Participants will also answer the year that they regularly played the games, frequency, and duration of play in open-ended questions for the game in their essay. These responses will be used for exploratory analyses (“When did you play game X?” [Example answer: 2010-2012]; “How frequently and long did you play the game X?” [Example answer: 2 times a week for 6 months]). Finally, participants will complete the attention check.

### Study 3
After playing the video game, participants will complete the Heart Manikin. Then, participants will indicate whether they interacted with the non-player characters in their essay (Yes or No). If the answer is Yes, they will complete the modified Inclusion of Self in Other Scale (Aron et al., 1992) and the Parasocial Interaction—Process Scale (Schramm & Hartmann, 2008). Lastly, participants will complete the Enjoyment Subscale of the Game User Experience Satisfaction Scale (GUESS; Phan et al., 2016) and the attention check items.

## Indices
<!-- If any measurements are  going to be combined into an index (or even a mean), what measures will you use and how will they be combined? Include either a formula or a precise description of your method. If your are using a more complicated statistical method to combine measures (e.g. a factor analysis), you can note that here but describe the exact method in the analysis plan section.

If you are using multiple pieces of data to construct a single variable, how will this occur? Both the data that are included and the formula or weights for each measure must be specified. Standard summary statistics, such as "means" do not require a formula, though more complicated indices require either the exact formula or, if it is an established index in the field, the index must be unambiguously defined. For example, "biodiversity index" is too broad, whereas "Shannon’s biodiversity index" is appropriate.

Example: We will take the mean of the two questions above to create a single measure of 'brownie enjoyment.'  -->

Below is the table of measures and indices for across studies. 

| Measure | Index |
|---------|-------|
|Heart Manikin| raw score |
| Self-Assessment Manikins | raw score |
| \setlength\parskip{12pt} \setlength\parindent{24pt} **Study 1a: Mass Testing**|
| CES-D | sum score |
| Beliefs about Biological Differences between Blacks and Whites Scale. |  average (11 items) |
| Interpersonal Reactivity Scale. | average score |
| Self-Monitoring Scale | sum  |
| Paradox Mindset Scale | average  |
| Multiple Identity Scale | average  | 
| Study 1b: RAIv1 |
| PROMIS Social Isolation, Emotional Support, and Informational Support—Short Form 8a | average | 
| Couples Satisfaction Index—4-item version | average |
| Inclusion of Other in Self Scale | average |
| Relationship Conflict Scale | average |
| Abusive Behavior Inventory—Psychological Abuse & Physical Abuse Subscales | average |
| Controlling Behavior Scale—Modified | average |
| Modified Food Cravings Questionnaire—Trait Version | average |
| Dietary Social Support Scale | average | 
| Body Image Questionnaire| the weekly leisure-time activity scores: (9 x Strenuous) + (5 x Moderate) + (3 x Mild). People with the scores of 24 and more had lower body fat percentage and higher maximum rate of oxygen consumption (VO2 max) than those with scores of 23 or less (Amireault & Godin, 2015)|
| PROMIS Sleep Disturbance—Short Form 4a | average |
| Single-Item Narcissism Scale | raw score |
| Perceived Stress Scale | average as an index |
| **Study 1b: ARv1** |
| Social Interaction Anxiety Scale | average |
| Modified Need-Threat Scale—Essay Version | average |
| State Self-Esteem Scale | average |
|  **Study 1c: EVv1** |
| Need for Closure Scale |  average |
| Social Judgment Survey | raw score |
|  **Study 1d: NPSv2** |
| Modified Need-Threat Scale | average |
| Experiences in Close Relationships Scale—Short Form | average |
| Fear of Negative Evaluation Scale—Brief Version | average |
| Rosenberg Self-Esteem Scale | average |
| MacArthur Scale of Subjective Social Status | raw score |
| Rejection Sensitivity Questionnaire—Short Version | average across the product of (a) anxiety and (b) expectation and averaging |
|  **Study 2** |
| Modified Inclusion of Self in Other Scale—Parasocial Relationship with Characters | raw score |
| Modified Narrative Engagement Scale | average |
| Enjoyment Subscale of the Game User Experience Satisfaction Scale (GUESS) | average | 
|  **Study 3** |
| **Same as Study 2*|


# Analysis Plan
<!-- You may describe one or more confirmatory analysis in this preregistration. Please remember that all analyses specified below must be reported in the final article, and any additional analyses must be noted as exploratory or hypothesis generating.

A confirmatory analysis plan must state up front which variables are predictors (independent) and which are the outcomes (dependent), otherwise it is an exploratory analysis. You are allowed to describe any exploratory work here, but a clear confirmatory analysis is required. -->


## Statistical models
<!-- What statistical model will you use to test each hypothesis? Please include the type of model (e.g. ANOVA, multiple regression, SEM, etc) and the specification of the model (this includes each variable that will be included as predictors, outcomes, or covariates). Please specify any interactions, subgroup analyses, pairwise or complex contrasts, or follow-up tests from omnibus tests. If you plan on using any positive controls, negative controls, or manipulation checks you may mention that here. Remember that any test not included here must be noted as an exploratory test in your final article.

This is perhaps the most important and most complicated question within the preregistration. As with all of the other questions, the key is to provide a specific recipe for analyzing the collected data. Ask yourself: is enough detail provided to run the same analysis again with the information provided by the user? Be aware for instances where the statistical models appear specific, but actually leave openings for the precise test. See the following examples:

- If someone specifies a 2x3 ANOVA with both factors within subjects, there is still flexibility with the various types of ANOVAs that could be run. Either a repeated measures ANOVA (RMANOVA) or a multivariate ANOVA (MANOVA) could be used for that design, which are two different tests. 
- If you are going to perform a sequential analysis and check after 50, 100, and 150 samples, you must also specify the p-values you’ll test against at those three points.

Example:  We will use a one-way between subjects ANOVA to analyze our results. The manipulated, categorical independent variable is 'sugar' whereas the dependent variable is our taste index. -->

### Study 1
To examine convergent validity, I will test an association between the  measures used in the study and the Heart Manikin. I will use an alpha of .05 as a cutoff point for statistical significance. To examine discriminant validity, I will use an equivalence test (Lakens, 2017) since a non-significant relationship is not an absence of a relationship in a null-hypothesis testing. To do so, I will set the smallest effect size of interest (SESOI) that is the minimal effect size that I consider theoretically meaningful. Any effect size that is lower than this effect size will be considered theoretically negligible, and thus equivalent to zero. To determine the SESOI, I will first use the average effect size (r = .21) derived from 474 meta-analytic effect sizes (with more than 25,000 studies) in social psychology (Richard et al., 2003). I first transformed this estimate (r = .21) to Fisher’s z (Fisher’s z = .21) for normality (Borenstein, 2019). To safeguard against the inflation of effect size, I consider the lower bound of the 60% confidence interval as the target effect size (Perugini et al., 2014). To calculate the confidence interval, I first calculated the standard error for the Fisher’s z using the sample size of 474, treating each meta-analytic effect size independently, SEz=1474-3=0.046 (Borenstein, 2019). Then, I calculated the confidence interval using the normal distribution. The lower bound of the 60% confidence interval was Fisher’s z = 0.17 (Fisher z = 0.21, 60%CI[0.17, 0.25]), which was equivalent to r = 0.17 and Cohen’s d = 0.35. Thus, I will set the SESOI as r = .17. I will compare any non-significant observed coefficient with the SESOI to see if the observed effect size is significantly smaller. To examine the test-retest reliability, I will calculate ICCs and interpret them as poor (<.50), moderate (.50–.75), good (.75–.90), and excellent (>.90) based on existing guidelines (Koo & Li, 2016). 
Studies 1b, 1c, 1d, and 1e include data where participants completed the Heart Manikin and other measures across multiple time points. To account for the dependency in data, I will use a linear mixed model. I will describe fixed predictors under each study section. I will first include both random intercept and the random effect of Time. If the model does not converge, I will remove the random effect of Time from the model. If the model converges, I will retain the random Time effect. To determine the structure of the residual variance-covariance matrix (R matrix) and the random-effects variance-covariance structure (G matrix), I will test models with different structures and choose the one that fits the data best. For the R matrix, I will test diagonal, compound symmetry, and unstructured structures. For the G matrix, I will test identity, variance components, and unstructured structures. 

#### Study 1a

#### Study 1b

#### Study 1c

#### Study 1d

#### Study 1e 


### Study 2
I will perform Welch's t-test to compare the belonging of rejected participants who wrote about the social surrogacy video game with rejected participants who wrote about the social surrogacy video game. Based on the social surrogacy hypothesis, I expect that participants who wrote about the social surrogacy video game will have higher belonging than those who wrote about the non-social surrogacy video game.
 If the obtained p-value is greater than .05, I will perform the two one-sided tests of equivalence to examine if the obtained effect size is theoretically equivalent to zero (Lakens, 2017). I will consider the effect size of d = 0.35 as the smallest effect size of interest (SESOI). Thus, any effect sizes between d = -0.35 and d = 0.35 are theoretically equivalent to zero. To compare the observed effect size with the SESOI, I will calculate the 90% confidence interval around the observed effect size. Then, I will compare this confidence interval with d = -0.35 and d = 0.35. I will set the confidence to 90% because the TOST procedure involves two one-sided tests each with a 5% alpha (Lakens, 2017). If the observed effect size estimate falls within -0.35 < d < 0.35, and its observed confidence interval does not include d = -0.35 or d = 0.35, I will consider that the observed effect size is equivalent to zero. 


### Study 3
I will run a 2 (Parasocial Relationships: High vs. Low) x 2 (Social Worlds: High vs. Low) ANOVA on the belonging scores. I plan to test the main effect of the parasocial relationships (Hypothesis 2) and the main effect of the social worlds (Hypothesis 3). In addition, I plan to compare the belonging scores of those in the Low Parasocial Relationships and Low Social Worlds condition to those in the High Parasocial Relationships and High Social Worlds condition to test Hypothesis 4. For each analysis, I will use p = .05 as an alpha level. Based on the social surrogacy hypothesis, I expect that (a) participants in the higher parasocial relationship condition will report higher belonging than those in the lower parasocial relationship condition, (b) participants in the higher social world condition will report higher belonging than those in the lower social world condition, and (c) participants in the higher parasocial relationship and higher social world conditions will report higher belonging than those in the lower parasocial relationship and lower social world condition. 



## Transformations
<!-- If you plan on transforming, centering, recoding the data, or will require a coding scheme for categorical variables, please describe that process. If any categorical predictors are included in a regression, indicate how those variables will be coded (e.g. dummy coding, summation coding, etc.) and what the reference category will be.

Example: The "Effect of sugar on brownie tastiness" does not require any additional transformations. However, if it were using a regression analysis and each level of sweet had been categorically described (e.g. not sweet, somewhat sweet, sweet, and very sweet), 'sweet' could be dummy coded with 'not sweet' as the reference category. -->

### Study 1a
No transformations.

### Study 1b
The fixed effects of Time will be coded as 1–3 categorical variable. The scores of a measure will be centered.

### Study 1c
- each measured score (centered)
- Social Rejection (-0.5 = Rejection, 0.5 = Acceptance)
- Essay Target (-0.5 = Stranger, 0.5 = Close Friend)

### Study 1d
- each measured score (centered)
- Time (categorical)
- Confederate Desire (.5 = high, -.5 = low)
- Rejection (.5 = rejection, -.5 = acceptance)

### Study 1e
- a dummy categorical variable (Grouping Dummy) representing the four experimental conditions for Participant Desire and Confederate Desire to reduce the number of interactions in the model (coded as 0-3)
- the measured scores (centered)
- Time (categorical)
- social rejection (rejected = -.5, control = .5)

## Inference criteria
<!-- What criteria will you use to make inferences? Please describe the information youÍll use (e.g. p-values, bayes factors, specific model fit indices), as well as cut-off criterion, where appropriate. Will you be using one or two tailed tests for each of your analyses? If you are comparing multiple conditions or testing multiple hypotheses, will you account for this?

p-values, confidence intervals, and effect sizes are standard means for making an inference, and any level is acceptable, though some criteria must be specified in this or previous fields. Bayesian analyses should specify a Bayes factor or a credible interval. If you are selecting models, then how will you determine the relative quality of each? In regards to multiple comparisons, this is a question with few "wrong" answers. In other words, transparency is more important than any specific method of controlling the false discovery rate or false error rate. One may state an intention to report all tests conducted or one may conduct a specific correction procedure; either strategy is acceptable.

Example: We will use the standard p<.05 criteria for determining if the ANOVA and the post hoc test suggest that the results are significantly different from those expected if the null hypothesis were correct. The post-hoc Tukey-Kramer test adjusts for multiple comparisons. -->

Across studies, I will use p = .05 as an alpha level

*Studies 2 & 3 Main Analysis.* If the obtained p-value is greater than .05, I will perform the two one-sided tests of equivalence to examine if the obtained effect size is theoretically equivalent to zero (Lakens, 2017). I will consider the effect size of d = 0.35 as the smallest effect size of interest (SESOI). Thus, any effect sizes between d = -0.35 and d = 0.35 are theoretically equivalent to zero. To compare the observed effect size with the SESOI, I will calculate the 90% confidence interval around the observed effect size. Then, I will compare this confidence interval with d = -0.35 and d = 0.35. I will set the confidence to 90% because the TOST procedure involves two one-sided tests each with a 5% alpha (Lakens, 2017). If the observed effect size estimate falls within -0.35 < d < 0.35, and its observed confidence interval does not include d = -0.35 or d = 0.35, I will consider that the observed effect size is equivalent to zero. 





## Data exclusion
<!-- How will you determine what data or samples, if any, to exclude from your analyses? How will outliers be handled? Will you use any awareness check? Any rule for excluding a particular set of data is acceptable. One may describe rules for excluding a participant or for identifying outlier data.

Example: No checks will be performed to determine eligibility for inclusion besides verification that each subject answered each of the three tastiness indices. Outliers will be included in the analysis. -->

For Studies 2 and 3, I will exclude any participants who fail to complete the entire study procedure or fail the attention check. 



## Missing data
<!-- How will you deal with incomplete or missing data? Any relevant explanation is acceptable. As a final reminder, remember that the final analysis must follow the specified plan, and deviations must be either strongly justified or included as a separate, exploratory analysis.

Example: If a subject does not complete any of the three indices of tastiness, that subject will not be included in the analysis. -->

I will exclude any participant who has a missing score.

## Exploratory analyses (optional)
<!-- If you plan to explore your data set to look for unexpected differences or relationships, you may describe those tests here. An exploratory test is any test where a prediction is not made up front, or there are multiple possible tests that you are going to use. A statistically significant finding in an exploratory test is a great way to form a new confirmatory hypothesis, which could be registered at a later time.

Example: We expect that certain demographic traits may be related to taste preferences. Therefore, we will look for relationships between demographic variables (age, gender, income, and marital status) and the primary outcome measures of taste preferences. -->

### Study 2
**Probing Effectiveness of Rejection Induction.** I will probe the effectiveness of the rejection induction by comparing using the Heart Manikin scores at Times 1 and 2. I will create a regression model predicting the Time 2 Heart Manikin scores with the following predictors: Time 1 Heart Manikin scores, Video Game Essay (Effect-Coded as Social Surrogates  = 0.5 and Non-Social Surrogates = -0.5), and the Time 1 Heart Manikin x Video Game Essay interaction. I will perform simple slope analyses to estimate whether belonging changed over time within the social surrogacy and non-social surrogacy game conditions, separately.  

**Exploratory Manipulation Check.** To explore the effectiveness of the video game essay manipulation in inducing parasocial relationships, I will use the combination of two sources of information: the yes/no question about the presence of parasocial interaction (i.e., whether participants interacted with the non-player characters in their essay), and the modified Inclusion of Self in the Other Scale (Aron et al., 1992). I will code each participant into three groups as follows. If a participant indicates that they did not interact with non-player characters (answering no to the yes/no question), they will be coded as “did not interact with non-player characters” (Group 1). If they indicate yes, and they score 0 on the modified Inclusion of Self in the Other Scale (Aron et al., 1992), they will be coded as “interacted with non-player characters but did not form parasocial relationships” (Group 2). All others will receive a code “interacted with non-player characters and formed parasocial relationships” (Group 3).  I will run a two-way chi-square test (Essay: Social Surrogacy vs. Non-Social Surrogacy x Groups: 1, 2, vs. 3) to examine whether those in the social surrogacy essay condition (vs. the non-social surrogacy condition) indicated they interacted with an NPCs (Group 2) and formed parasocial relationships (Group 3) rather than they did not interact with non-player characters (Group 1). This procedure allows participants to indicate that they did not interact with non-player characters, a response option not available in the modified Inclusion of Self in the Other Scale (Aron et al., 1992).

To explore the effectiveness of the video game essay in inducing social worlds, I will run a Welch’s t-test to compare the scores of the Single-Item Immersion Scale (Reysen et al., 2019) and the Narrative Engagement Scale, between social surrogate vs. non-social surrogate video game essay conditions. I expect that rejected participants who wrote about the social surrogacy video game will report higher immersion compared with those who wrote about their non-social surrogacy video game. 

Note that both the Inclusion of Self in the Other Scale (Aron et al., 1992) and the Single-Item Immersion Scale (Reysen et al., 2019) have never been validated to measure social surrogates in video games, and thus I treat these analyses as exploratory. A failed manipulation check in this context can be ambiguous—such results can imply that (a) the manipulation was ineffective to induce parasocial relationships and social worlds, or (b) the measures were ineffective to capture the manipulated constructs. Accordingly, I will not conclude the effectiveness of the manipulation based on these exploratory analyses.

**Exploratory Analysis of Enjoyment across Social Surrogacy vs. Non-Social Surrogacy Games.** To explore whether levels of enjoyment differed for social Surrogacy vs. non-social Surrogacy video conditions, I will perform Welch’s t-test on the enjoyment scores. I have no a priori hypothesis for this analysis. 

#### Study 3
**Exploratory Manipulation Check.** To explore the effectiveness of the parasocial relationship manipulation, I will again use the procedure in Study 2 to code the participants into three groups: “did not interact with non-player characters” (Group 1), “interacted with non-player characters but did not form parasocial relationships” (Group 2)”, and “interacted with non-player characters and formed parasocial relationships” (Group 3). Then, I will run a two-way chi-square test (Parasocial Relationships: High vs. Low x Groups: 1, 2, vs. 3) to examine whether those in the social surrogacy essay condition (vs. the non-social surrogacy condition) indicated they interacted with NPCs (Group 2) and formed parasocial relationships (Group 3) more, rather than they did not interact with non-player characters (Group 1).  For the social world manipulation, I will run Welch's t-test to compare the scores of the Single-Item Immersion Scale (Reysen et al., 2019) and the Narrative Engagement Scale between the High vs. Low social worlds conditions. I expect that participants who played a video game with higher social worlds will report higher immersion to the social worlds than those who played a video game with lower social worlds. Consistent with Study 2, I will treat the manipulation checks as exploratory and will not conclude the effectiveness of the manipulation based on these exploratory analyses. 

**Exploratory Moderation Analysis.** I will explore whether the gender or race of participants moderated the effect of the parasocial relationships and the social worlds on belonging using regression. For each demographic characteristic, I will construct a regression model predicting belonging with the following predictors: Parasocial Relationships (.5 = high, -.5 = low), Social Worlds (.5 = high, -.5 = low), Gender (.5 = female, -.5 = male) or Race (four dummy variables representing: American-Indian, African American/Black, White/Caucasian, Asian/Pacific Islander, and other), and their fully-crossed interaction terms.  

# Other

## Other (Optional)
<!-- If there is any additional information that you feel needs to be included in your preregistration, please enter it here. Literature cited, disclosures of any related work such as replications or work that uses the same data, or other context that will be helpful for future readers would be appropriate here. -->

Enter your response here.


# References

<!-- \vspace{-2pc} -->
<!-- \setlength{\parindent}{-0.5in} -->
<!-- \setlength{\leftskip}{-1in} -->
<!-- \setlength{\parskip}{8pt} -->
<!-- \noindent -->
