---
title: "Study 3 Prioritizing Participants"
output: html_notebook
---

```{r}
# Load Libraries
library(tidyverse)
library(here)
library(codebook)

# Codebook Setup
knitr::opts_chunk$set(
  warning = TRUE, # show warnings during codebook generation
  message = TRUE, # show messages during codebook generation
  error = TRUE, # do not interrupt codebook generation in case of errors,
                # usually better for debugging
  echo = TRUE  # show R code
)
ggplot2::theme_set(ggplot2::theme_bw())
```


```{r}
# Read the csv
input_csv <- "RPR_2021_03_15.csv"
eligibility <- read_csv(here("data/RPR", input_csv), col_names = FALSE, skip = 3) 
eligibility_colnames <- read_csv(here("data/RPR", input_csv), col_names = FALSE, n_max = 1)
eligibility_labels <- read_csv(here("data/RPR", input_csv), col_names = FALSE, n_max = 1, skip = 1) %>% 
  pivot_longer(-1)
colnames(eligibility) <- eligibility_colnames


GAMES_df <- eligibility %>% 
  select(id, Q314:Q325)

```


Checking if the questions were presented correctly
```{r}
eligibility_labels %>% select(-1) %>%
  filter(name %in% paste0("X", 215:226))
```



```{r}
# Codebook to make the labels 
add_labels_GAMES <- function(x) {
  val_labels(x) <- c("Strongly disagree" = 1,
                     "Somewhat disagree" = 2,
                     "Neither agree nor disagree" = 3, 
                     "Somewhat agree" = 4,
                     "Strongly agree" = 5)
  return(x)
}


reversed_items <- c("GAMES1", "GAMES2", "GAMES3")

# Rename Columns
GAMES_df <- GAMES_df %>%
  mutate(across(Q314:Q325,
         ~case_when(. == "Strongly agree" ~ 5,
                    . == "Somewhat agree" ~ 4,
                    . == "Neither agree nor disagree" ~ 3,
                    . == "Somewhat disagree" ~ 2,
                    . == "Strongly disagree" ~ 1))) %>%
  mutate_at(vars(Q314:Q325), add_labels_GAMES) %>%
  rename_at(vars(-id),  ~ paste0("GAMES", 1:12))


# Reverse Code 
GAMES_df_rev <- GAMES_df %>% 
  rename_at(reversed_items,
                add_R) %>%
  # Reverse the values 
    mutate_at(vars(matches("\\dR$")), reverse_labelled_values)


# Add Scale
GAMES_df_rev$GAMES <- GAMES_df_rev %>% 
  select(GAMES1R:GAMES12) %>% 
  aggregate_and_document_scale()


# Divide people into quartiles?
codebook(GAMES_df_rev)
```

Output the csv file for export.

Divide folks to Quantiles
```{r}
GAMES_df_rev <- GAMES_df_rev %>% 
  mutate(quantile = ntile(GAMES, n = 4),
         Like_Stories = quantile)
```

```{r}
# Histogram
GAMES_df_rev %>%
  ggplot(aes(x = GAMES)) + geom_histogram(aes(y = ..density..)) + 
  geom_density(aes(y = ..density..))

```

Export
```{r}
# Export
GAMES_df_rev %>% select(id, Like_Stories) %>%
  drop_na() %>% arrange(desc(Like_Stories)) %>%
  write_csv(here("data/Sunami_Screening.csv"))
```

