---
title: "R Notebook"
output: html_notebook
---

# Study 2 

```{r}
library(tidyverse)
library(here)
s2favorite_n <- 344/2
heart_sd <- 1.916658
target_d <- 0.35

# heart_norm <- rnorm(s2favorite_n, mean = 5, sd = 1.916658) %>% round()
#
mysamp <- function(n, m, s, lwr, upr, nnorm) {
  samp <- rnorm(nnorm, m, s)
  samp <- samp[samp >= lwr & samp <= upr]
  if (length(samp) >= n) {
    return(sample(samp, n))
  }  
  stop(simpleError("Not enough values to sample from. Try increasing nnorm."))
}

set.seed(42)
heart_norm <- mysamp(n=s2favorite_n, m=5, s=heart_sd, lwr=1, upr=9, nnorm=1000) %>% round()

heart_favorite <- mysamp(n=s2favorite_n, m= 5 + (heart_sd * target_d)/2, s=heart_sd, lwr=1, upr=9, nnorm=1000)

heart_nfavorite <- mysamp(n=s2favorite_n, m= 5 - (heart_sd * target_d)/2, s=heart_sd, lwr=1, upr=9, nnorm=1000)

heart_favorite %>% qplot()
heart_nfavorite %>% qplot()

study2_df <- tibble(Condition = c(
  rep("Favorite", length(heart_favorite)),
  rep("Non-favorite", length(heart_nfavorite))),
  Heart = c(heart_favorite, heart_nfavorite))
```

```{r}
t.test(formula = Heart ~ Condition, data = study2_df)
```

```{r}
ggplot(data = study2_df,
       aes(x = Condition, y = Heart, fill = Condition)) + 
  geom_violin() +
  stat_summary(fun.data = mean_cl_normal, 
               fun.args = list(conf.int = .95),
               geom = "errorbar", width = .3) + 
    geom_point(stat = "summary", fun.data = mean_se) +
  scale_y_continuous(limits = c(0, 10),
                     breaks = 1:9) + 
  theme_minimal()
```

reference:
https://stackoverflow.com/questions/19343133/setting-upper-and-lower-limits-in-rnorm
```{r}
mysamp_pois <- function(n, m, s, lwr, upr, nnorm) {
  samp <- rpois(nnorm, m)
  samp <- samp[samp >= lwr & samp <= upr]
  if (length(samp) >= n) {
    return(sample(samp, n))
  }  
  stop(simpleError("Not enough values to sample from. Try increasing nnorm."))
}

set.seed(123)

mean_heart <- 

heart_favorite_pois <- mysamp_pois(n=s2favorite_n, m= 7 + heart_sd * target_d, s=heart_sd, lwr=1, upr=9, nnorm=1000)
heart_nfavorite_pois <- mysamp_pois(n=s2favorite_n, m= 7 - heart_sd * target_d, s=heart_sd, lwr=1, upr=9, nnorm=1000)

study2_df_pois <- tibble(Condition = c(
  rep("Favorite", length(heart_favorite_pois)),
  rep("Non-favorite", length(heart_nfavorite_pois))),
  Heart = c(heart_favorite_pois, heart_nfavorite_pois))


t.test(formula = Heart ~ Condition, data = study2_df_pois)

heart_favorite_pois %>% qplot()
heart_nfavorite_pois %>% qplot()
```


```{r}
ggplot(data = study2_df_pois,
       aes(x = Condition, y = Heart, fill = Condition)) + 
  geom_violin(width = .6) +
  stat_summary(fun.data = mean_cl_normal, 
               fun.args = list(conf.int = .95),
               geom = "errorbar", width = .3) + 
    geom_point(stat = "summary", fun.data = mean_se) +
  scale_y_continuous(limits = c(0, 10),
                     breaks = 1:9) + 
  theme_minimal() +
  scale_fill_brewer(palette = "Set2") +
  guides(fill = FALSE) + 
  ggtitle(label = "Study 2 Expected Results") +
  ylab("Belonging") +
  xlab("Video Game Essay") +
  ggsave(here("plot","s2_plot.png"), width = 3, height = 3)

```


# Study 3
```{r}
lpara_lsoc <- mysamp_pois(n=s2favorite_n/2, m= 7 - (heart_sd * target_d) * 2, s=heart_sd, lwr=1, upr=9, nnorm=1000)
hpara_lsoc <- mysamp_pois(n=s2favorite_n/2, m= 7, s=heart_sd, lwr=1, upr=9, nnorm=1000)
lpara_hsoc <- mysamp_pois(n=s2favorite_n/2, m= 7, s=heart_sd, lwr=1, upr=9, nnorm=1000)

hpara_hsoc <- mysamp_pois(n=s2favorite_n/2, m= 7 + (heart_sd * target_d) * 2, s=heart_sd, lwr=1, upr=9, nnorm=1000)

s3_df <- tibble(
  `Parasocial Relationships` = c(
    rep("Low", length(lpara_lsoc)),
    rep("High", length(hpara_lsoc)),
    rep("Low", length(lpara_hsoc)),
    rep("High", length(hpara_hsoc))),
  `Social Worlds` = c(
    rep("Low", length(lpara_lsoc)),
    rep("Low", length(hpara_lsoc)),
    rep("High", length(lpara_hsoc)),
    rep("High", length(hpara_hsoc))),
  `Heart`= c(lpara_lsoc, hpara_lsoc, lpara_hsoc, hpara_hsoc)
  )


```



```{r}
s3_plot <- ggplot(data = s3_df,
       aes(x = `Parasocial Relationships`, y = Heart, fill = `Social Worlds`)) + 
  geom_violin(position = position_dodge(width = 1)) +
  stat_summary(fun.data = mean_cl_normal, 
               fun.args = list(conf.int = .95),
               geom = "errorbar", width = .3,
               position = position_dodge(width = 1)) + 
    geom_point(stat = "summary", fun.data = mean_se,
               position = position_dodge(width = 1)) +
  scale_y_continuous(limits = c(0, 10),
                     breaks = 1:9) + 
  theme_minimal() +
  scale_fill_brewer(palette = "Set2") +
  ggtitle(label = "Study 3 Expected Results") +
  ylab("Belonging") + 
  ggsave(here("plot","s3_plot.png"), width = 4.5, height = 3)

s3_plot
```


